Some minor models and views update
mrojaczy/buildlease pull request #7
Opened 2021-10-25 13:12 UTC by rosteeslove

To better fit the frontend template

2021-10-25 18:25 UTC, aperaverzeu approved these changes
Good

2021-10-25 19:34 UTC, Rigorich requested changes

2021-10-25 19:34 UTC, Rigorich commented on Buildlease/Contracts/Views/ProductOrderView.cs
> +        public int Id { get; set; }
rename to `ProductId`, because `Id` is `ProductOrderId`

2021-10-25 19:34 UTC, Rigorich commented on Buildlease/Contracts/Views/ProductOrderView.cs
> +        public string ShortDescription { get; set; }
Протестую: излишне.

2021-10-25 19:35 UTC, rosteeslove commented on Buildlease/Contracts/Views/ProductOrderView.cs
> +        public string ShortDescription { get; set; }
Предлагаешь изменить шаблон страниц корзины и сделанного заказа?

2021-10-25 19:36 UTC, rosteeslove commented on Buildlease/Contracts/Views/ProductOrderView.cs
> +        public int Id { get; set; }
Fine

2021-10-25 19:43 UTC, Rigorich commented on Buildlease/Contracts/Views/ProductOrderView.cs
> +        public string ShortDescription { get; set; }
Да, убрать краткую строку описания

2021-10-26 14:12 UTC, Rigorich approved these changes

2021-10-26 14:13 UTC, Rigorich approved these changes

2021-10-26 19:50 UTC, merged